# enums.py

from enum import Enum

class Constants(Enum):
    BOARD_SIZE = 21,
    BENCH_SIZE = 11,
    SHOP_SIZE = 5,
    MAX_CHAMPION_ID = 100,
    MAX_CHAMPION_COST = 10,
    MAX_CHAMPION_LEVEL = 3,
    MAX_ITEMS_PER_CHAMPION = 6,
    MAX_ITEM_ID = 100,
    MAX_LEVEL = 10,
    MAX_HEALTH = 100,
    MAX_EXPERIENCE = 100,
    MAX_GOLD = 500,
    MAX_EXPERIENCE_TO_NEXT_LEVEL = 100,
    NUM_ACTIONS = 100,
    NUM_OPPONENTS = 7